- name: Install Jenkins on EC2 instance
  hosts: all
  gather_facts: true
  vars:
    ansible_python_interpreter: /usr/bin/python3.8

  tasks:
    - name: Set ansible_distribution fact
      set_fact:
       ansible_distribution: Ubuntu
 
    - name: Download Jenkins WAR file
      become: true
      get_url:
        url: "https://get.jenkins.io/war-stable/latest/jenkins.war"
        dest: /opt/jenkins.war

    - name: Create jenkins user
      become: true
      command: useradd -m -s /bin/bash -r jenkins
      ignore_errors: yes

    - name: Set ownership and permissions for Jenkins WAR file
      become: true
      file:
        path: /opt/jenkins.war
        owner: jenkins
        group: jenkins
        mode: "0644"

    - name: Create systemd service file for Jenkins
      become: true
      template:
        src: jenkins.service.j2
        dest: /etc/systemd/system/jenkins.service

    - name: Reload systemd to load the new service file
      become: true
      systemd:
        daemon_reload: yes

    - name: Start Jenkins service
      become: true
      service:
        name: jenkins
        state: started
        enabled: yes

    # - name: Wait for Jenkins to start
    #   wait_for:
    #     host: all
    #     port: 8080
    #     state: started
    #     timeout: 300

        
